version: '3.4'

services:
  booksapi:
    image: ${DOCKER_REGISTRY-}aspnetcoremicroservicesbooksapi
    build:
      context: .
      dockerfile: AspNetCoreMicroservices.Books.Api/Dockerfile

  jokesapi:
    image: ${DOCKER_REGISTRY-}aspnetcoremicroservicesjokesapi
    build:
      context: .
      dockerfile: AspNetCoreMicroservices.Jokes.Api/Dockerfile

  frontend:
    image: ${DOCKER_REGISTRY-}aspnetcoremicroservicesfrontend
    build:
      context: .
      dockerfile: AspNetCoreMicroservices.Frontend/Dockerfile
    depends_on:
      - booksapi
      - jokesapi
