version: '2'

services:
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BookCatalogUrl=http://bookcatalog.api
      - PricingUrl=http://pricing.api
      - RatingUrl=http://rating.api
    ports:
      - "80"

  bookcatalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Database=bookcatalog;User Id=sa;Password=Pass@word
    ports:
      - "80"

  pricing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  rating.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Database=rating;User Id=sa;Password=Pass@word
    ports:
      - "80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"