version: '2'

services:
  webmvc:
    image: webmvc
    build:
      context: ./src/Frontend/WebMVC
      dockerfile: Dockerfile
    depends_on:
      - bookcatalog.api
      - pricing.api
      - rating.api

  bookcatalog.api:
    image: bookcatalog.api
    build:
      context: ./src/Services/BookCatalog/BookCatalog.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  pricing.api:
    image: pricing.api
    build:
      context: ./src/Services/Pricing/Pricing.API
      dockerfile: Dockerfile

  rating.api:
    image: rating.api
    build:
      context: ./src/Services/Rating/Rating.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux